################################################################################
# Ocarina travis-ci configuration file.
# This script compiles and test Ocarina for Linux and OS X targets
#
# Note: this travis-ci script is adapted from
# https://github.com/AdaCore/Ada_Drivers_Library
#
# Thanks to AdaCore for providing it

################################################################################
# Note: we are using 'generic' as a language. We need GNAT to compile
# Ocarina, and Python to run Ocarina testsuite. We install a specific
# GNAT GPL release to compile and run everything.

language: generic
osx_image: xcode8.3

# Global variables
env:
  global:
    - TOOLS_DIR=$HOME/build_tools
    - GNAT_TAR_PATH=$TOOLS_DIR/gnat-gpl-2016-bin.tar.gz

################################################################################
# Host to run the various tests
os:
  - linux
  - osx

################################################################################
# Install the build environment, derived from travis default installation

# 1/ Cache directory that allows us to not download GNAT GPL every time,
# speeding up the process.

cache:
  directories:
  - $HOME/build_tools

# 2/ Check Python installation

before_install:
- which python

# 3/ Install GNAT GPL 2016

install:
  # Check if the GNAT package is already available in the cache directory. If
  # not, download it.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -f  $GNAT_TAR_PATH ||( mkdir -p $TOOLS_DIR && wget http://mirrors.cdn.adacore.com/art/5739cefdc7a447658e0b016b -O $GNAT_TAR_PATH); fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then test -f  $GNAT_TAR_PATH ||( mkdir -p $TOOLS_DIR && wget http://mirrors.cdn.adacore.com/art/573a396cc7a447658d00e430 -O $GNAT_TAR_PATH); fi

  # Extract GNAT from its package
  - tar -xf $GNAT_TAR_PATH

  # Add GNAT to $PATH
  - export PATH=$PWD/gnat-gpl-2016-x86_64-linux-bin/bin/:$PWD/gnat-gpl-2016-x86_64-darwin-bin/bin/:$PATH

################################################################################
# Main processing starts here

script:
  # Show GNAT version for the record
  - gcc --version
  - gnatls -v

  # Just build
  - git clone https://github.com/OpenAADL/ocarina-build.git ; ( cd ocarina-build ; ./build_ocarina.sh --scenario=travis-ci )

# Codecov.io
after_success:
  - bash <(curl -s https://codecov.io/bash)

################################################################################
#

before_deploy:
  - export OCARINA_SRC=$(find . -name "*tar.gz")
  - echo $OCARINA_SRC
  - export OCARINA_BIN=$(find . -name "*tgz")
  - echo $OCARINA_BIN

deploy:
  provider: releases
  api_key:
    secure: JIs5VZq+T0m42jasHpuDHXjJwgmQNGDaNJos9xHG01b5tvrG9NRIPjB4AFh1RiJBQ8LYFRpcRkrEzbAHs9H4jh7zLrdaAGRo6v0G/h5aowWNGoTiT6sMy5ATX6cuMO/treCEWWEUpUsDy5GSebsRkGhbMjH3d2kZ3933SJIg+kI=
  skip_cleanup: true
  file:
    - "${OCARINA_SRC}"
    - "${OCARINA_BIN}"
  on:
    tags: true
    all_branches: true
