SUBDIRS= test001 \
			test002 \
			test003 \
			test004 \
			test005 \
			test006 \
			test007 \
			test008 \
			test009 \
			test010 \
			test011 \
			test012 \
			test013 \
			test014 \
			test015 \
			test016 \
			test017 \
			test018 \
			test019 \
			test020 \
			test021 \
			test022 \
			test023 \
			test024 \
			test025 \
			test026 \
			test027 \
			test028 \
			test029 \
			test030 \
			test031 \
			test032 \
			test033 \
			test034 \
			test_aadl_min \
			osate-access-connection-directions \
			osate-access-connection-multidest \
			osate-access-connection-types \
			osate-access-matching \
			osate-aggregate-port-group \
			osate-bogus-refinement \
			osate-bug68 \
			osate-call-ordering \
			osate-call-seq-and-modes \
			osate-circular-extension \
			osate-connection-category \
			osate-connection-directions \
			osate-connection-modes-and-transitions \
			osate-data-connections \
			osate-deterministic-transitions \
			osate-dispatch-port \
			osate-end-to-end \
			osate-flow-dirs \
			osate-flow-impl-modes \
			osate-flow-impls \
			osate-initial-mode \
			osate-inverse-of-chains \
			osate-inverse-of-extensions \
			osate-modal-connections \
			osate-modal-parameter-connection \
			osate-modal-parameter-connection2 \
			osate-mode-transition-ports \
			osate-multi-refinement \
			osate-multiple-sources \
			osate-package-section \
			osate-parameter-connection-modes \
			osate-parameter-connection-types \
			osate-parameter-connections \
			osate-parameter-refinement \
			osate-port-group-connection \
			osate-port-group-connections \
			osate-port-group-inverse \
			osate-port-refinement \
			osate-server-subprogram \
			osate-subcomponent-access \
			osate2-t01 \
			osate2-t02 \
			osate2-t03 \
			osate2-t04 \
			osate2-t05 \
			osate2-t06 \
			osate2-t07 \
			osate2-t08 \
			osate2-t09 \
			osate2-t10 \
			osate2-t11 \
			osate2-t12 \
			osate2-t13 \
			osate2-t14 \
			osate2-t15 \
			osate2-t16 \
			osate2-t17 \
			flow-huge \
			flow-rc-integrated \
			SAE-standard-examples-09152005 \
			SAE-test-examples-09152005 \
			test_tree_i \
			test_tree_p \
			po-hi-c/ping \
			po-hi-c/producer-consumer \
			po-hi-c/d3.1.3-1 \
			po-hi-c/flight-mgmt \
			po-hi-c/rma \
			po-hi-c/some-types \
			po-hi-c/some-types-stdint \
			po-hi-c/sunseeker  \
			test_ocarina_config \
			test_ocarina_gpr \
			po-hi-ada/d3.1.3-1 \
			po-hi-ada/d3.1.3-1_extended \
			po-hi-ada/delayed_connections \
			po-hi-ada/flight_mgmt \
			po-hi-ada/import \
			po-hi-ada/mode_switch \
			po-hi-ada/mpc \
			po-hi-ada/ping \
			po-hi-ada/producer_consumer \
			po-hi-ada/rma \
			po-hi-ada/some_types \
			po-hi-ada/subprogram_ports \
			po-hi-ada/sunseeker \
			LNT/FCS \
			LNT/PC \
			LNT/RADAR \
			LNT/ROBOT

