------------------------------------------------------------------------------
--                                                                          --
--                           OCARINA COMPONENTS                             --
--                                                                          --
--               O C A R I N A . B A C K E N D S . R O S                    --
--                                                                          --
--                                 B o d y                                  --
--                                                                          --
--                   Copyright (C) 2014-2016 ESA & ISAE.                    --
--                                                                          --
-- Ocarina  is free software; you can redistribute it and/or modify under   --
-- terms of the  GNU General Public License as published  by the Free Soft- --
-- ware  Foundation;  either version 3,  or (at your option) any later ver- --
-- sion. Ocarina is distributed in the hope that it will be useful, but     --
-- WITHOUT ANY WARRANTY; without even the implied warranty of               --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.                     --
--                                                                          --
-- As a special exception under Section 7 of GPL version 3, you are granted --
-- additional permissions described in the GCC Runtime Library Exception,   --
-- version 3.1, as published by the Free Software Foundation.               --
--                                                                          --
-- You should have received a copy of the GNU General Public License and    --
-- a copy of the GCC Runtime Library Exception along with this program;     --
-- see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see    --
-- <http://www.gnu.org/licenses/>.                                          --
--                                                                          --
--                 Ocarina is maintained by the TASTE project               --
--                      (taste-users@lists.tuxfamily.org)                   --
--                                                                          --
------------------------------------------------------------------------------

with Charset;           use Charset;
with Ocarina.Namet;
with Ocarina.ME_AADL;
with Ocarina.ME_AADL.AADL_Instances.Nodes;
with Ocarina.ME_AADL.AADL_Tree.Nodes;
with Ocarina.Instances; use Ocarina.Instances;
with Ocarina.ME_AADL.AADL_Instances.Entities;
use Ocarina.ME_AADL.AADL_Instances.Entities;

with Ocarina.Backends.Utils;
with Ada.Text_IO;

package body Ocarina.Backends.Ros is

   package AIN renames Ocarina.ME_AADL.AADL_Instances.Nodes;
   package ATN renames Ocarina.ME_AADL.AADL_Tree.Nodes;

   use Ocarina.Namet;
   use Ada.Text_IO;
   use Ocarina.ME_AADL;
   use Ocarina.Backends.Utils;
   use AIN;

   FD               : File_Type;
   Root_System_Name : Name_Id;

   ----------
   -- Init --
   ----------

   procedure Init is
   begin
      --  Registration of the generator

      Register_Backend ("ros", Generate'Access, Ros_Backend);
   end Init;

   --------------
   -- Generate --
   --------------

   procedure Generate (AADL_Root : Node_Id) is
      Instance_Root : Node_Id;

   begin
      --  Instantiate the AADL tree

      Instance_Root := Instantiate_Model (AADL_Root);
      if No (Instance_Root) then
         raise Program_Error;
      end if;

      --  Open a new .als file

      Create (File => FD, Name => "output.launch");

      Put_Line (FD, "<!-- This file has been generated by Ocarina -->");
      Put_Line (FD, "<!-- Handle with care -->");
      Put_Line (FD, "<launch>");
      
      declare
         Print_Subcomponents : Boolean          := True;
         E                   : constant Node_Id := Root_System (Instance_Root);
         T                   : Node_Id;
      begin
         Put_Line("Check for processes");
         if Present (Subcomponents (E)) then
            T := First_Node (Subcomponents (E));
            while Present (T) loop
               Print_Subcomponents :=
                 Print_Subcomponents
                 and then (Get_Category_Of_Component (T) = CC_Process);
               T := Next_Node (T);
            end loop;
         end if;

         Put_Line("Check complete");

         if Print_Subcomponents then
            Put_Line("processes found"); 
            if Present (Subcomponents (E)) then
               T := First_Node (Subcomponents (E));
               while Present (T) loop
                  declare
                      Subcomponent_name: constant String := Get_Name_String(Display_Name(Identifier(T)));
                      Classifier_name: constant String := Get_Name_String(Display_Name(Identifier(Corresponding_Instance(T))));
                  begin
                      --TODO Find the name of the file
                      --TODO Problem with implementation naming (The .)
                      Put_Line(FD, "<node pkg=""test"" type=""" & Classifier_name & """ name=""" & Subcomponent_name & """ />");
                  end;
                  T := Next_Node (T);
               end loop;
            else
               Put_Line (FD, "none");
            end if;
         end if;
      end;

      Put_Line (FD, "</launch>");

      --  Close file descriptor

      Close (FD);
   end Generate;

   -----------
   -- Reset --
   -----------

   procedure Reset is
   begin
      null;
   end Reset;

end Ocarina.Backends.Ros;
