pragma Ada_95;
pragma Source_File_Name (ada_main, Spec_File_Name => "b~ocarina_cmd.ads");
pragma Source_File_Name (ada_main, Body_File_Name => "b~ocarina_cmd.adb");
pragma Suppress (Overflow_Check);
with Ada.Exceptions;

package body ada_main is
   pragma Warnings (Off);

   E138 : Short_Integer; pragma Import (Ada, E138, "gnat__spelling_checker_E");
   E072 : Short_Integer; pragma Import (Ada, E072, "system__os_lib_E");
   E011 : Short_Integer; pragma Import (Ada, E011, "system__soft_links_E");
   E367 : Short_Integer; pragma Import (Ada, E367, "system__fat_flt_E");
   E119 : Short_Integer; pragma Import (Ada, E119, "system__fat_llf_E");
   E021 : Short_Integer; pragma Import (Ada, E021, "system__exception_table_E");
   E533 : Short_Integer; pragma Import (Ada, E533, "ada__containers_E");
   E059 : Short_Integer; pragma Import (Ada, E059, "ada__io_exceptions_E");
   E363 : Short_Integer; pragma Import (Ada, E363, "ada__numerics_E");
   E087 : Short_Integer; pragma Import (Ada, E087, "ada__strings_E");
   E089 : Short_Integer; pragma Import (Ada, E089, "ada__strings__maps_E");
   E092 : Short_Integer; pragma Import (Ada, E092, "ada__strings__maps__constants_E");
   E043 : Short_Integer; pragma Import (Ada, E043, "ada__tags_E");
   E058 : Short_Integer; pragma Import (Ada, E058, "ada__streams_E");
   E070 : Short_Integer; pragma Import (Ada, E070, "interfaces__c_E");
   E023 : Short_Integer; pragma Import (Ada, E023, "system__exceptions_E");
   E075 : Short_Integer; pragma Import (Ada, E075, "system__file_control_block_E");
   E551 : Short_Integer; pragma Import (Ada, E551, "ada__streams__stream_io_E");
   E064 : Short_Integer; pragma Import (Ada, E064, "system__file_io_E");
   E068 : Short_Integer; pragma Import (Ada, E068, "system__finalization_root_E");
   E066 : Short_Integer; pragma Import (Ada, E066, "ada__finalization_E");
   E545 : Short_Integer; pragma Import (Ada, E545, "system__regpat_E");
   E203 : Short_Integer; pragma Import (Ada, E203, "system__storage_pools_E");
   E199 : Short_Integer; pragma Import (Ada, E199, "system__finalization_masters_E");
   E197 : Short_Integer; pragma Import (Ada, E197, "system__storage_pools__subpools_E");
   E518 : Short_Integer; pragma Import (Ada, E518, "system__task_info_E");
   E394 : Short_Integer; pragma Import (Ada, E394, "ada__calendar_E");
   E400 : Short_Integer; pragma Import (Ada, E400, "ada__calendar__time_zones_E");
   E813 : Short_Integer; pragma Import (Ada, E813, "ada__command_line__response_file_E");
   E082 : Short_Integer; pragma Import (Ada, E082, "gnat__directory_operations_E");
   E530 : Short_Integer; pragma Import (Ada, E530, "gnat__directory_operations__iteration_E");
   E150 : Short_Integer; pragma Import (Ada, E150, "system__assertions_E");
   E211 : Short_Integer; pragma Import (Ada, E211, "system__pool_global_E");
   E015 : Short_Integer; pragma Import (Ada, E015, "system__secondary_stack_E");
   E191 : Short_Integer; pragma Import (Ada, E191, "ada__strings__unbounded_E");
   E392 : Short_Integer; pragma Import (Ada, E392, "ada__directories_E");
   E540 : Short_Integer; pragma Import (Ada, E540, "gnat__expect_E");
   E218 : Short_Integer; pragma Import (Ada, E218, "system__regexp_E");
   E189 : Short_Integer; pragma Import (Ada, E189, "gnat__command_line_E");
   E549 : Short_Integer; pragma Import (Ada, E549, "system__strings__stream_ops_E");
   E499 : Short_Integer; pragma Import (Ada, E499, "ada__real_time_E");
   E056 : Short_Integer; pragma Import (Ada, E056, "ada__text_io_E");
   E469 : Short_Integer; pragma Import (Ada, E469, "gnat__io_aux_E");
   E132 : Short_Integer; pragma Import (Ada, E132, "charset_E");
   E108 : Short_Integer; pragma Import (Ada, E108, "ocarina_E");
   E883 : Short_Integer; pragma Import (Ada, E883, "ocarina__be_real_E");
   E811 : Short_Integer; pragma Import (Ada, E811, "ocarina__cmd_line_E");
   E869 : Short_Integer; pragma Import (Ada, E869, "ocarina__configuration_E");
   E815 : Short_Integer; pragma Import (Ada, E815, "ocarina__fe_aadl_E");
   E885 : Short_Integer; pragma Import (Ada, E885, "ocarina__fe_aadl_ba_E");
   E912 : Short_Integer; pragma Import (Ada, E912, "ocarina__fe_aadl_ema_E");
   E922 : Short_Integer; pragma Import (Ada, E922, "ocarina__fe_ao4aadl_E");
   E859 : Short_Integer; pragma Import (Ada, E859, "ocarina__fe_real_E");
   E867 : Short_Integer; pragma Import (Ada, E867, "ocarina__scripts_E");
   E148 : Short_Integer; pragma Import (Ada, E148, "ocarina__types_E");
   E168 : Short_Integer; pragma Import (Ada, E168, "locations_E");
   E077 : Short_Integer; pragma Import (Ada, E077, "errors_E");
   E221 : Short_Integer; pragma Import (Ada, E221, "ocarina__analyzer_E");
   E223 : Short_Integer; pragma Import (Ada, E223, "ocarina__analyzer__aadl_E");
   E225 : Short_Integer; pragma Import (Ada, E225, "ocarina__analyzer__aadl__annexes_E");
   E306 : Short_Integer; pragma Import (Ada, E306, "ocarina__analyzer__aadl__legality_rules_E");
   E308 : Short_Integer; pragma Import (Ada, E308, "ocarina__analyzer__aadl__links_E");
   E312 : Short_Integer; pragma Import (Ada, E312, "ocarina__analyzer__aadl__names_E");
   E229 : Short_Integer; pragma Import (Ada, E229, "ocarina__analyzer__aadl__naming_rules_E");
   E273 : Short_Integer; pragma Import (Ada, E273, "ocarina__analyzer__aadl__queries_E");
   E310 : Short_Integer; pragma Import (Ada, E310, "ocarina__analyzer__aadl__semantics_E");
   E314 : Short_Integer; pragma Import (Ada, E314, "ocarina__analyzer__aadl_ba_E");
   E325 : Short_Integer; pragma Import (Ada, E325, "ocarina__analyzer__aadl_ema_E");
   E331 : Short_Integer; pragma Import (Ada, E331, "ocarina__analyzer__aadl_ema__links_E");
   E329 : Short_Integer; pragma Import (Ada, E329, "ocarina__analyzer__aadl_ema__naming_rules_E");
   E340 : Short_Integer; pragma Import (Ada, E340, "ocarina__analyzer__real_E");
   E170 : Short_Integer; pragma Import (Ada, E170, "ocarina__annotations_E");
   E373 : Short_Integer; pragma Import (Ada, E373, "ocarina__backends_E");
   E375 : Short_Integer; pragma Import (Ada, E375, "ocarina__backends__aadl_xml_E");
   E377 : Short_Integer; pragma Import (Ada, E377, "ocarina__backends__aadl_xml__main_E");
   E379 : Short_Integer; pragma Import (Ada, E379, "ocarina__backends__aadl_xml__mapping_E");
   E687 : Short_Integer; pragma Import (Ada, E687, "ocarina__backends__ada_tree__generator_E");
   E407 : Short_Integer; pragma Import (Ada, E407, "ocarina__backends__ada_tree__nodes_E");
   E411 : Short_Integer; pragma Import (Ada, E411, "ocarina__backends__ada_tree__nutils_E");
   E415 : Short_Integer; pragma Import (Ada, E415, "ocarina__backends__ada_values_E");
   E429 : Short_Integer; pragma Import (Ada, E429, "ocarina__backends__alloy_E");
   E431 : Short_Integer; pragma Import (Ada, E431, "ocarina__backends__arinc653_conf_E");
   E433 : Short_Integer; pragma Import (Ada, E433, "ocarina__backends__arinc653_conf__connections_E");
   E440 : Short_Integer; pragma Import (Ada, E440, "ocarina__backends__arinc653_conf__memory_E");
   E442 : Short_Integer; pragma Import (Ada, E442, "ocarina__backends__arinc653_conf__module_hm_E");
   E444 : Short_Integer; pragma Import (Ada, E444, "ocarina__backends__arinc653_conf__partition_hm_E");
   E446 : Short_Integer; pragma Import (Ada, E446, "ocarina__backends__arinc653_conf__partitions_E");
   E448 : Short_Integer; pragma Import (Ada, E448, "ocarina__backends__arinc653_conf__scheduling_E");
   E450 : Short_Integer; pragma Import (Ada, E450, "ocarina__backends__arinc653_conf__system_hm_E");
   E452 : Short_Integer; pragma Import (Ada, E452, "ocarina__backends__asn1_E");
   E454 : Short_Integer; pragma Import (Ada, E454, "ocarina__backends__asn1__deployment_E");
   E465 : Short_Integer; pragma Import (Ada, E465, "ocarina__backends__asn1_tree__generator_E");
   E457 : Short_Integer; pragma Import (Ada, E457, "ocarina__backends__asn1_tree__nodes_E");
   E463 : Short_Integer; pragma Import (Ada, E463, "ocarina__backends__asn1_values_E");
   E461 : Short_Integer; pragma Import (Ada, E461, "ocarina__backends__asn1_tree__nutils_E");
   E467 : Short_Integer; pragma Import (Ada, E467, "ocarina__backends__boundt_E");
   E487 : Short_Integer; pragma Import (Ada, E487, "ocarina__backends__c_common__subprograms_E");
   E491 : Short_Integer; pragma Import (Ada, E491, "ocarina__backends__c_common__types_E");
   E495 : Short_Integer; pragma Import (Ada, E495, "ocarina__backends__c_tree__generator_E");
   E474 : Short_Integer; pragma Import (Ada, E474, "ocarina__backends__c_tree__nodes_E");
   E478 : Short_Integer; pragma Import (Ada, E478, "ocarina__backends__c_tree__nutils_E");
   E483 : Short_Integer; pragma Import (Ada, E483, "ocarina__backends__c_values_E");
   E581 : Short_Integer; pragma Import (Ada, E581, "ocarina__backends__cheddar_E");
   E583 : Short_Integer; pragma Import (Ada, E583, "ocarina__backends__cheddar__main_E");
   E585 : Short_Integer; pragma Import (Ada, E585, "ocarina__backends__cheddar__mapping_E");
   E587 : Short_Integer; pragma Import (Ada, E587, "ocarina__backends__connection_matrix_E");
   E589 : Short_Integer; pragma Import (Ada, E589, "ocarina__backends__connection_matrix__main_E");
   E591 : Short_Integer; pragma Import (Ada, E591, "ocarina__backends__deos_conf_E");
   E593 : Short_Integer; pragma Import (Ada, E593, "ocarina__backends__deos_conf__hm_E");
   E595 : Short_Integer; pragma Import (Ada, E595, "ocarina__backends__deos_conf__naming_E");
   E599 : Short_Integer; pragma Import (Ada, E599, "ocarina__backends__deos_conf__partitions_E");
   E615 : Short_Integer; pragma Import (Ada, E615, "ocarina__backends__deos_conf__schedule_E");
   E425 : Short_Integer; pragma Import (Ada, E425, "ocarina__backends__expander_E");
   E619 : Short_Integer; pragma Import (Ada, E619, "ocarina__backends__functions_matrix_E");
   E621 : Short_Integer; pragma Import (Ada, E621, "ocarina__backends__functions_matrix__main_E");
   E623 : Short_Integer; pragma Import (Ada, E623, "ocarina__backends__lnt_E");
   E625 : Short_Integer; pragma Import (Ada, E625, "ocarina__backends__lnt__nodes_E");
   E639 : Short_Integer; pragma Import (Ada, E639, "ocarina__backends__lnt__components_E");
   E629 : Short_Integer; pragma Import (Ada, E629, "ocarina__backends__lnt__nutils_E");
   E631 : Short_Integer; pragma Import (Ada, E631, "ocarina__backends__lnt__printer_E");
   E633 : Short_Integer; pragma Import (Ada, E633, "ocarina__backends__lnt__svl_generator_E");
   E635 : Short_Integer; pragma Import (Ada, E635, "ocarina__backends__lnt__tree_generator_E");
   E637 : Short_Integer; pragma Import (Ada, E637, "ocarina__backends__lnt__tree_generator_main_E");
   E641 : Short_Integer; pragma Import (Ada, E641, "ocarina__backends__lnt__tree_generator_port_E");
   E643 : Short_Integer; pragma Import (Ada, E643, "ocarina__backends__lnt__tree_generator_processor_E");
   E645 : Short_Integer; pragma Import (Ada, E645, "ocarina__backends__lnt__tree_generator_thread_E");
   E647 : Short_Integer; pragma Import (Ada, E647, "ocarina__backends__lnt__tree_generator_types_E");
   E649 : Short_Integer; pragma Import (Ada, E649, "ocarina__backends__mast_E");
   E651 : Short_Integer; pragma Import (Ada, E651, "ocarina__backends__mast__main_E");
   E662 : Short_Integer; pragma Import (Ada, E662, "ocarina__backends__mast_tree__generator_E");
   E654 : Short_Integer; pragma Import (Ada, E654, "ocarina__backends__mast_tree__nodes_E");
   E660 : Short_Integer; pragma Import (Ada, E660, "ocarina__backends__mast_tree__nutils_E");
   E658 : Short_Integer; pragma Import (Ada, E658, "ocarina__backends__mast_values_E");
   E417 : Short_Integer; pragma Import (Ada, E417, "ocarina__backends__messages_E");
   E664 : Short_Integer; pragma Import (Ada, E664, "ocarina__backends__pn_E");
   E666 : Short_Integer; pragma Import (Ada, E666, "ocarina__backends__pn__components_E");
   E679 : Short_Integer; pragma Import (Ada, E679, "ocarina__backends__pn__format__cami_E");
   E681 : Short_Integer; pragma Import (Ada, E681, "ocarina__backends__pn__format__tina_E");
   E672 : Short_Integer; pragma Import (Ada, E672, "ocarina__backends__pn__iutils_E");
   E670 : Short_Integer; pragma Import (Ada, E670, "ocarina__backends__pn__nodes_E");
   E674 : Short_Integer; pragma Import (Ada, E674, "ocarina__backends__pn__nutils_E");
   E683 : Short_Integer; pragma Import (Ada, E683, "ocarina__backends__pn__printer_E");
   E676 : Short_Integer; pragma Import (Ada, E676, "ocarina__backends__pn__utils_E");
   E685 : Short_Integer; pragma Import (Ada, E685, "ocarina__backends__po_hi_ada_E");
   E689 : Short_Integer; pragma Import (Ada, E689, "ocarina__backends__po_hi_ada__activity_E");
   E695 : Short_Integer; pragma Import (Ada, E695, "ocarina__backends__po_hi_ada__deployment_E");
   E697 : Short_Integer; pragma Import (Ada, E697, "ocarina__backends__po_hi_ada__main_E");
   E699 : Short_Integer; pragma Import (Ada, E699, "ocarina__backends__po_hi_ada__marshallers_E");
   E701 : Short_Integer; pragma Import (Ada, E701, "ocarina__backends__po_hi_ada__naming_E");
   E693 : Short_Integer; pragma Import (Ada, E693, "ocarina__backends__po_hi_ada__runtime_E");
   E703 : Short_Integer; pragma Import (Ada, E703, "ocarina__backends__po_hi_ada__subprograms_E");
   E705 : Short_Integer; pragma Import (Ada, E705, "ocarina__backends__po_hi_ada__transport_E");
   E707 : Short_Integer; pragma Import (Ada, E707, "ocarina__backends__po_hi_ada__types_E");
   E485 : Short_Integer; pragma Import (Ada, E485, "ocarina__backends__po_hi_c_E");
   E569 : Short_Integer; pragma Import (Ada, E569, "ocarina__backends__po_hi_c__activity_E");
   E571 : Short_Integer; pragma Import (Ada, E571, "ocarina__backends__po_hi_c__deployment_E");
   E573 : Short_Integer; pragma Import (Ada, E573, "ocarina__backends__po_hi_c__main_E");
   E575 : Short_Integer; pragma Import (Ada, E575, "ocarina__backends__po_hi_c__marshallers_E");
   E577 : Short_Integer; pragma Import (Ada, E577, "ocarina__backends__po_hi_c__naming_E");
   E579 : Short_Integer; pragma Import (Ada, E579, "ocarina__backends__po_hi_c__request_E");
   E489 : Short_Integer; pragma Import (Ada, E489, "ocarina__backends__po_hi_c__runtime_E");
   E493 : Short_Integer; pragma Import (Ada, E493, "ocarina__backends__pok_c_E");
   E555 : Short_Integer; pragma Import (Ada, E555, "ocarina__backends__pok_c__activity_E");
   E559 : Short_Integer; pragma Import (Ada, E559, "ocarina__backends__pok_c__deployment_E");
   E561 : Short_Integer; pragma Import (Ada, E561, "ocarina__backends__pok_c__main_E");
   E563 : Short_Integer; pragma Import (Ada, E563, "ocarina__backends__pok_c__makefile_E");
   E565 : Short_Integer; pragma Import (Ada, E565, "ocarina__backends__pok_c__naming_E");
   E557 : Short_Integer; pragma Import (Ada, E557, "ocarina__backends__pok_c__runtime_E");
   E567 : Short_Integer; pragma Import (Ada, E567, "ocarina__backends__pok_cheddar_E");
   E421 : Short_Integer; pragma Import (Ada, E421, "ocarina__backends__properties_E");
   E435 : Short_Integer; pragma Import (Ada, E435, "ocarina__backends__arinc653_conf__mapping_E");
   E471 : Short_Integer; pragma Import (Ada, E471, "ocarina__backends__build_utils_E");
   E481 : Short_Integer; pragma Import (Ada, E481, "ocarina__backends__c_common__mapping_E");
   E597 : Short_Integer; pragma Import (Ada, E597, "ocarina__backends__deos_conf__mapping_E");
   E497 : Short_Integer; pragma Import (Ada, E497, "ocarina__backends__execution_tests_E");
   E532 : Short_Integer; pragma Import (Ada, E532, "ocarina__backends__execution_utils_E");
   E691 : Short_Integer; pragma Import (Ada, E691, "ocarina__backends__po_hi_ada__mapping_E");
   E617 : Short_Integer; pragma Import (Ada, E617, "ocarina__backends__properties__arinc653_E");
   E769 : Short_Integer; pragma Import (Ada, E769, "ocarina__backends__replication_properties_E");
   E735 : Short_Integer; pragma Import (Ada, E735, "ocarina__backends__replication_expander_E");
   E771 : Short_Integer; pragma Import (Ada, E771, "ocarina__backends__stats_E");
   E773 : Short_Integer; pragma Import (Ada, E773, "ocarina__backends__stats__main_E");
   E775 : Short_Integer; pragma Import (Ada, E775, "ocarina__backends__stats__mapping_E");
   E777 : Short_Integer; pragma Import (Ada, E777, "ocarina__backends__subprograms_E");
   E390 : Short_Integer; pragma Import (Ada, E390, "ocarina__backends__utils_E");
   E779 : Short_Integer; pragma Import (Ada, E779, "ocarina__backends__vxworks653_conf_E");
   E781 : Short_Integer; pragma Import (Ada, E781, "ocarina__backends__vxworks653_conf__connections_E");
   E785 : Short_Integer; pragma Import (Ada, E785, "ocarina__backends__vxworks653_conf__hm_E");
   E783 : Short_Integer; pragma Import (Ada, E783, "ocarina__backends__vxworks653_conf__mapping_E");
   E787 : Short_Integer; pragma Import (Ada, E787, "ocarina__backends__vxworks653_conf__naming_E");
   E789 : Short_Integer; pragma Import (Ada, E789, "ocarina__backends__vxworks653_conf__partitions_E");
   E791 : Short_Integer; pragma Import (Ada, E791, "ocarina__backends__vxworks653_conf__payloads_E");
   E793 : Short_Integer; pragma Import (Ada, E793, "ocarina__backends__vxworks653_conf__schedule_E");
   E438 : Short_Integer; pragma Import (Ada, E438, "ocarina__backends__xml_common__mapping_E");
   E427 : Short_Integer; pragma Import (Ada, E427, "ocarina__backends__xml_tree__generator_E");
   E382 : Short_Integer; pragma Import (Ada, E382, "ocarina__backends__xml_tree__nodes_E");
   E388 : Short_Integer; pragma Import (Ada, E388, "ocarina__backends__xml_tree__nutils_E");
   E386 : Short_Integer; pragma Import (Ada, E386, "ocarina__backends__xml_values_E");
   E795 : Short_Integer; pragma Import (Ada, E795, "ocarina__backends__xtratum_conf_E");
   E797 : Short_Integer; pragma Import (Ada, E797, "ocarina__backends__xtratum_conf__channels_E");
   E799 : Short_Integer; pragma Import (Ada, E799, "ocarina__backends__xtratum_conf__hardware_description_E");
   E807 : Short_Integer; pragma Import (Ada, E807, "ocarina__backends__xtratum_conf__mapping_E");
   E801 : Short_Integer; pragma Import (Ada, E801, "ocarina__backends__xtratum_conf__partition_table_E");
   E803 : Short_Integer; pragma Import (Ada, E803, "ocarina__backends__xtratum_conf__resident_sw_E");
   E805 : Short_Integer; pragma Import (Ada, E805, "ocarina__backends__xtratum_conf__system_description_E");
   E809 : Short_Integer; pragma Import (Ada, E809, "ocarina__backends__xtratum_conf__xm_hypervisor_E");
   E825 : Short_Integer; pragma Import (Ada, E825, "ocarina__builder__aadl__annexes_E");
   E279 : Short_Integer; pragma Import (Ada, E279, "ocarina__builder__aadl__components_E");
   E841 : Short_Integer; pragma Import (Ada, E841, "ocarina__builder__aadl__components__arrays_E");
   E283 : Short_Integer; pragma Import (Ada, E283, "ocarina__builder__aadl__components__connections_E");
   E285 : Short_Integer; pragma Import (Ada, E285, "ocarina__builder__aadl__components__features_E");
   E287 : Short_Integer; pragma Import (Ada, E287, "ocarina__builder__aadl__components__flows_E");
   E289 : Short_Integer; pragma Import (Ada, E289, "ocarina__builder__aadl__components__modes_E");
   E849 : Short_Integer; pragma Import (Ada, E849, "ocarina__builder__aadl__components__prototypes_E");
   E291 : Short_Integer; pragma Import (Ada, E291, "ocarina__builder__aadl__components__subcomponents_E");
   E293 : Short_Integer; pragma Import (Ada, E293, "ocarina__builder__aadl__components__subprogram_calls_E");
   E281 : Short_Integer; pragma Import (Ada, E281, "ocarina__builder__aadl__namespaces_E");
   E277 : Short_Integer; pragma Import (Ada, E277, "ocarina__builder__aadl__properties_E");
   E898 : Short_Integer; pragma Import (Ada, E898, "ocarina__builder__aadl_ba__actions_E");
   E902 : Short_Integer; pragma Import (Ada, E902, "ocarina__builder__aadl_ba__expressions_E");
   E894 : Short_Integer; pragma Import (Ada, E894, "ocarina__builder__aadl_ba__specifications_E");
   E908 : Short_Integer; pragma Import (Ada, E908, "ocarina__builder__aadl_ba__thread_dispatch_E");
   E344 : Short_Integer; pragma Import (Ada, E344, "ocarina__builder__real_E");
   E914 : Short_Integer; pragma Import (Ada, E914, "ocarina__fe_aadl_ema__parser_E");
   E924 : Short_Integer; pragma Import (Ada, E924, "ocarina__fe_ao4aadl__parser_E");
   E861 : Short_Integer; pragma Import (Ada, E861, "ocarina__fe_real__parser_E");
   E301 : Short_Integer; pragma Import (Ada, E301, "ocarina__files_E");
   E237 : Short_Integer; pragma Import (Ada, E237, "ocarina__instances_E");
   E241 : Short_Integer; pragma Import (Ada, E241, "ocarina__instances__annexes_E");
   E239 : Short_Integer; pragma Import (Ada, E239, "ocarina__instances__components_E");
   E243 : Short_Integer; pragma Import (Ada, E243, "ocarina__instances__components__connections_E");
   E257 : Short_Integer; pragma Import (Ada, E257, "ocarina__instances__components__features_E");
   E247 : Short_Integer; pragma Import (Ada, E247, "ocarina__instances__components__modes_E");
   E259 : Short_Integer; pragma Import (Ada, E259, "ocarina__instances__components__subcomponents_E");
   E249 : Short_Integer; pragma Import (Ada, E249, "ocarina__instances__components__subprogram_calls_E");
   E251 : Short_Integer; pragma Import (Ada, E251, "ocarina__instances__messages_E");
   E253 : Short_Integer; pragma Import (Ada, E253, "ocarina__instances__namespaces_E");
   E262 : Short_Integer; pragma Import (Ada, E262, "ocarina__instances__processor__properties_E");
   E245 : Short_Integer; pragma Import (Ada, E245, "ocarina__instances__properties_E");
   E358 : Short_Integer; pragma Import (Ada, E358, "ocarina__instances__queries_E");
   E356 : Short_Integer; pragma Import (Ada, E356, "ocarina__instances__real_checker__queries_E");
   E709 : Short_Integer; pragma Import (Ada, E709, "ocarina__backends__real_E");
   E713 : Short_Integer; pragma Import (Ada, E713, "ocarina__instances__real_checker__queries__relational_predicates_E");
   E179 : Short_Integer; pragma Import (Ada, E179, "ocarina__me_aadl__aadl_instances__entities_E");
   E183 : Short_Integer; pragma Import (Ada, E183, "ocarina__me_aadl__aadl_instances__nodes_E");
   E255 : Short_Integer; pragma Import (Ada, E255, "ocarina__instances__finder_E");
   E177 : Short_Integer; pragma Import (Ada, E177, "ocarina__me_aadl__aadl_instances__nutils_E");
   E185 : Short_Integer; pragma Import (Ada, E185, "ocarina__me_aadl__aadl_tree__entities_E");
   E164 : Short_Integer; pragma Import (Ada, E164, "ocarina__me_aadl__aadl_tree__nodes_E");
   E110 : Short_Integer; pragma Import (Ada, E110, "ocarina__aadl_values_E");
   E227 : Short_Integer; pragma Import (Ada, E227, "ocarina__analyzer__aadl__finder_E");
   E231 : Short_Integer; pragma Import (Ada, E231, "ocarina__analyzer__messages_E");
   E423 : Short_Integer; pragma Import (Ada, E423, "ocarina__backends__properties__utils_E");
   E360 : Short_Integer; pragma Import (Ada, E360, "ocarina__me_aadl__aadl_instances__entities__properties_E");
   E233 : Short_Integer; pragma Import (Ada, E233, "ocarina__me_aadl__aadl_tree__entities__properties_E");
   E187 : Short_Integer; pragma Import (Ada, E187, "ocarina__me_aadl__aadl_tree__nutils_E");
   E264 : Short_Integer; pragma Import (Ada, E264, "ocarina__me_aadl__printers_E");
   E317 : Short_Integer; pragma Import (Ada, E317, "ocarina__me_aadl_ba__ba_tree__nodes_E");
   E321 : Short_Integer; pragma Import (Ada, E321, "ocarina__me_aadl_ba__ba_tree__nutils_E");
   E299 : Short_Integer; pragma Import (Ada, E299, "ocarina__me_aadl_ema__ema_tokens_E");
   E920 : Short_Integer; pragma Import (Ada, E920, "ocarina__fe_aadl_ema__parser_errors_E");
   E334 : Short_Integer; pragma Import (Ada, E334, "ocarina__me_aadl_ema__ema_tree__nodes_E");
   E327 : Short_Integer; pragma Import (Ada, E327, "ocarina__analyzer__aadl_ema__finder_E");
   E916 : Short_Integer; pragma Import (Ada, E916, "ocarina__ema_values_E");
   E338 : Short_Integer; pragma Import (Ada, E338, "ocarina__me_aadl_ema__ema_tree__nutils_E");
   E932 : Short_Integer; pragma Import (Ada, E932, "ocarina__me_ao4aadl__ao4aadl_tree__nodes_E");
   E926 : Short_Integer; pragma Import (Ada, E926, "ocarina__ao4aadl_values_E");
   E930 : Short_Integer; pragma Import (Ada, E930, "ocarina__me_ao4aadl__ao4aadl_tree__nutils_E");
   E938 : Short_Integer; pragma Import (Ada, E938, "ocarina__me_ao4aadl__tokens_E");
   E940 : Short_Integer; pragma Import (Ada, E940, "ocarina__fe_ao4aadl__parser_errors_E");
   E347 : Short_Integer; pragma Import (Ada, E347, "ocarina__me_real__real_tree__nodes_E");
   E353 : Short_Integer; pragma Import (Ada, E353, "ocarina__me_real__real_tree__nutils_E");
   E342 : Short_Integer; pragma Import (Ada, E342, "ocarina__analyzer__real__finder_E");
   E304 : Short_Integer; pragma Import (Ada, E304, "ocarina__me_real__tokens_E");
   E865 : Short_Integer; pragma Import (Ada, E865, "ocarina__fe_real__parser_errors_E");
   E136 : Short_Integer; pragma Import (Ada, E136, "ocarina__namet_E");
   E918 : Short_Integer; pragma Import (Ada, E918, "ocarina__fe_aadl_ema__lexer_E");
   E936 : Short_Integer; pragma Import (Ada, E936, "ocarina__fe_ao4aadl__lexer_E");
   E863 : Short_Integer; pragma Import (Ada, E863, "ocarina__fe_real__lexer_E");
   E767 : Short_Integer; pragma Import (Ada, E767, "ocarina__me_aadl__tokens_E");
   E737 : Short_Integer; pragma Import (Ada, E737, "ocarina__be_aadl_E");
   E741 : Short_Integer; pragma Import (Ada, E741, "ocarina__be_aadl__annexes_E");
   E739 : Short_Integer; pragma Import (Ada, E739, "ocarina__be_aadl__components_E");
   E751 : Short_Integer; pragma Import (Ada, E751, "ocarina__be_aadl__components__arrays_E");
   E753 : Short_Integer; pragma Import (Ada, E753, "ocarina__be_aadl__components__connections_E");
   E755 : Short_Integer; pragma Import (Ada, E755, "ocarina__be_aadl__components__features_E");
   E757 : Short_Integer; pragma Import (Ada, E757, "ocarina__be_aadl__components__flows_E");
   E743 : Short_Integer; pragma Import (Ada, E743, "ocarina__be_aadl__components__modes_E");
   E759 : Short_Integer; pragma Import (Ada, E759, "ocarina__be_aadl__components__prototypes_E");
   E761 : Short_Integer; pragma Import (Ada, E761, "ocarina__be_aadl__components__subcomponents_E");
   E763 : Short_Integer; pragma Import (Ada, E763, "ocarina__be_aadl__components__subprogram_calls_E");
   E745 : Short_Integer; pragma Import (Ada, E745, "ocarina__be_aadl__identifiers_E");
   E765 : Short_Integer; pragma Import (Ada, E765, "ocarina__be_aadl__namespaces_E");
   E747 : Short_Integer; pragma Import (Ada, E747, "ocarina__be_aadl__properties_E");
   E749 : Short_Integer; pragma Import (Ada, E749, "ocarina__be_aadl__properties__values_E");
   E819 : Short_Integer; pragma Import (Ada, E819, "ocarina__fe_aadl__lexer_E");
   E857 : Short_Integer; pragma Import (Ada, E857, "ocarina__fe_aadl__parser_errors_E");
   E817 : Short_Integer; pragma Import (Ada, E817, "ocarina__fe_aadl__parser_E");
   E823 : Short_Integer; pragma Import (Ada, E823, "ocarina__fe_aadl__parser__annexes_E");
   E827 : Short_Integer; pragma Import (Ada, E827, "ocarina__fe_aadl__parser__components_E");
   E839 : Short_Integer; pragma Import (Ada, E839, "ocarina__fe_aadl__parser__components__arrays_E");
   E829 : Short_Integer; pragma Import (Ada, E829, "ocarina__fe_aadl__parser__components__connections_E");
   E843 : Short_Integer; pragma Import (Ada, E843, "ocarina__fe_aadl__parser__components__features_E");
   E845 : Short_Integer; pragma Import (Ada, E845, "ocarina__fe_aadl__parser__components__flows_E");
   E831 : Short_Integer; pragma Import (Ada, E831, "ocarina__fe_aadl__parser__components__modes_E");
   E847 : Short_Integer; pragma Import (Ada, E847, "ocarina__fe_aadl__parser__components__prototypes_E");
   E851 : Short_Integer; pragma Import (Ada, E851, "ocarina__fe_aadl__parser__components__subcomponents_E");
   E853 : Short_Integer; pragma Import (Ada, E853, "ocarina__fe_aadl__parser__components__subprogram_calls_E");
   E833 : Short_Integer; pragma Import (Ada, E833, "ocarina__fe_aadl__parser__identifiers_E");
   E821 : Short_Integer; pragma Import (Ada, E821, "ocarina__fe_aadl__parser__namespaces_E");
   E835 : Short_Integer; pragma Import (Ada, E835, "ocarina__fe_aadl__parser__properties_E");
   E837 : Short_Integer; pragma Import (Ada, E837, "ocarina__fe_aadl__parser__properties__values_E");
   E296 : Short_Integer; pragma Import (Ada, E296, "ocarina__me_aadl_ba__tokens_E");
   E871 : Short_Integer; pragma Import (Ada, E871, "ocarina__be_aadl_ba_E");
   E875 : Short_Integer; pragma Import (Ada, E875, "ocarina__be_aadl_ba__actions_E");
   E877 : Short_Integer; pragma Import (Ada, E877, "ocarina__be_aadl_ba__expressions_E");
   E879 : Short_Integer; pragma Import (Ada, E879, "ocarina__be_aadl_ba__identifiers_E");
   E873 : Short_Integer; pragma Import (Ada, E873, "ocarina__be_aadl_ba__specifications_E");
   E881 : Short_Integer; pragma Import (Ada, E881, "ocarina__be_aadl_ba__thread_dispatch_E");
   E889 : Short_Integer; pragma Import (Ada, E889, "ocarina__fe_aadl_ba__lexer_E");
   E910 : Short_Integer; pragma Import (Ada, E910, "ocarina__fe_aadl_ba__parser_errors_E");
   E887 : Short_Integer; pragma Import (Ada, E887, "ocarina__fe_aadl_ba__parser_E");
   E896 : Short_Integer; pragma Import (Ada, E896, "ocarina__fe_aadl_ba__parser__actions_E");
   E900 : Short_Integer; pragma Import (Ada, E900, "ocarina__fe_aadl_ba__parser__expressions_E");
   E904 : Short_Integer; pragma Import (Ada, E904, "ocarina__fe_aadl_ba__parser__identifiers_E");
   E891 : Short_Integer; pragma Import (Ada, E891, "ocarina__fe_aadl_ba__parser__specifications_E");
   E906 : Short_Integer; pragma Import (Ada, E906, "ocarina__fe_aadl_ba__parser__thread_dispatch_E");
   E266 : Short_Integer; pragma Import (Ada, E266, "ocarina__options_E");
   E142 : Short_Integer; pragma Import (Ada, E142, "ocarina__output_E");
   E409 : Short_Integer; pragma Import (Ada, E409, "ocarina__backends__ada_tree__debug_E");
   E459 : Short_Integer; pragma Import (Ada, E459, "ocarina__backends__asn1_tree__debug_E");
   E476 : Short_Integer; pragma Import (Ada, E476, "ocarina__backends__c_tree__debug_E");
   E627 : Short_Integer; pragma Import (Ada, E627, "ocarina__backends__lnt__debug_E");
   E656 : Short_Integer; pragma Import (Ada, E656, "ocarina__backends__mast_tree__debug_E");
   E668 : Short_Integer; pragma Import (Ada, E668, "ocarina__backends__pn__debug_E");
   E384 : Short_Integer; pragma Import (Ada, E384, "ocarina__backends__xml_tree__debug_E");
   E181 : Short_Integer; pragma Import (Ada, E181, "ocarina__me_aadl__aadl_instances__debug_E");
   E166 : Short_Integer; pragma Import (Ada, E166, "ocarina__me_aadl__aadl_tree__debug_E");
   E319 : Short_Integer; pragma Import (Ada, E319, "ocarina__me_aadl_ba__ba_tree__debug_E");
   E336 : Short_Integer; pragma Import (Ada, E336, "ocarina__me_aadl_ema__ema_tree__debug_E");
   E934 : Short_Integer; pragma Import (Ada, E934, "ocarina__me_ao4aadl__ao4aadl_tree__debug_E");
   E349 : Short_Integer; pragma Import (Ada, E349, "ocarina__me_real__real_tree__debug_E");
   E351 : Short_Integer; pragma Import (Ada, E351, "ocarina__me_real__real_tree__utils_E");
   E729 : Short_Integer; pragma Import (Ada, E729, "ocarina__instances__real_finder_E");
   E855 : Short_Integer; pragma Import (Ada, E855, "ocarina__parser_E");
   E271 : Short_Integer; pragma Import (Ada, E271, "ocarina__processor__properties_E");
   E235 : Short_Integer; pragma Import (Ada, E235, "ocarina__property_sets_E");
   E369 : Short_Integer; pragma Import (Ada, E369, "ocarina__real_expander_E");
   E371 : Short_Integer; pragma Import (Ada, E371, "ocarina__real_expander__flow_analysis_E");
   E362 : Short_Integer; pragma Import (Ada, E362, "ocarina__real_values_E");
   E942 : Short_Integer; pragma Import (Ada, E942, "ocarina__transfo_E");
   E944 : Short_Integer; pragma Import (Ada, E944, "ocarina__transfo__fusions_E");
   E946 : Short_Integer; pragma Import (Ada, E946, "ocarina__transfo__fusions__scheduler_E");
   E948 : Short_Integer; pragma Import (Ada, E948, "ocarina__transfo__move_E");
   E950 : Short_Integer; pragma Import (Ada, E950, "ocarina__transfo__optim_E");
   E952 : Short_Integer; pragma Import (Ada, E952, "ocarina__transfo__optim__eval_E");
   E954 : Short_Integer; pragma Import (Ada, E954, "ocarina__utils_E");
   E268 : Short_Integer; pragma Import (Ada, E268, "outfiles_E");
   E174 : Short_Integer; pragma Import (Ada, E174, "utils_E");
   E711 : Short_Integer; pragma Import (Ada, E711, "ocarina__instances__real_checker__queries__access_predicates_E");
   E715 : Short_Integer; pragma Import (Ada, E715, "ocarina__instances__real_checker__queries__bound_predicates_E");
   E717 : Short_Integer; pragma Import (Ada, E717, "ocarina__instances__real_checker__queries__call_predicates_E");
   E719 : Short_Integer; pragma Import (Ada, E719, "ocarina__instances__real_checker__queries__connected_predicates_E");
   E721 : Short_Integer; pragma Import (Ada, E721, "ocarina__instances__real_checker__queries__passing_predicates_E");
   E723 : Short_Integer; pragma Import (Ada, E723, "ocarina__instances__real_checker__queries__predecessor_predicates_E");
   E725 : Short_Integer; pragma Import (Ada, E725, "ocarina__instances__real_checker__queries__provided_class_predicates_E");
   E727 : Short_Integer; pragma Import (Ada, E727, "ocarina__instances__real_checker__queries__subcomponent_predicates_E");

   Local_Priority_Specific_Dispatching : constant String := "";
   Local_Interrupt_States : constant String := "";

   Is_Elaborated : Boolean := False;

   procedure finalize_library is
   begin
      declare
         procedure F1;
         pragma Import (Ada, F1, "ocarina__backends__execution_tests__finalize_body");
      begin
         E497 := E497 - 1;
         F1;
      end;
      declare
         procedure F2;
         pragma Import (Ada, F2, "ocarina__backends__execution_tests__finalize_spec");
      begin
         F2;
      end;
      E056 := E056 - 1;
      declare
         procedure F3;
         pragma Import (Ada, F3, "ada__text_io__finalize_spec");
      begin
         F3;
      end;
      E392 := E392 - 1;
      E218 := E218 - 1;
      declare
         procedure F4;
         pragma Import (Ada, F4, "system__regexp__finalize_spec");
      begin
         F4;
      end;
      E540 := E540 - 1;
      declare
         procedure F5;
         pragma Import (Ada, F5, "gnat__expect__finalize_spec");
      begin
         F5;
      end;
      declare
         procedure F6;
         pragma Import (Ada, F6, "ada__directories__finalize_spec");
      begin
         F6;
      end;
      E191 := E191 - 1;
      declare
         procedure F7;
         pragma Import (Ada, F7, "ada__strings__unbounded__finalize_spec");
      begin
         F7;
      end;
      declare
         procedure F8;
         pragma Import (Ada, F8, "system__file_io__finalize_body");
      begin
         E064 := E064 - 1;
         F8;
      end;
      E199 := E199 - 1;
      E197 := E197 - 1;
      E211 := E211 - 1;
      declare
         procedure F9;
         pragma Import (Ada, F9, "system__pool_global__finalize_spec");
      begin
         F9;
      end;
      declare
         procedure F10;
         pragma Import (Ada, F10, "system__storage_pools__subpools__finalize_spec");
      begin
         F10;
      end;
      declare
         procedure F11;
         pragma Import (Ada, F11, "system__finalization_masters__finalize_spec");
      begin
         F11;
      end;
      E551 := E551 - 1;
      declare
         procedure F12;
         pragma Import (Ada, F12, "ada__streams__stream_io__finalize_spec");
      begin
         F12;
      end;
      declare
         procedure Reraise_Library_Exception_If_Any;
            pragma Import (Ada, Reraise_Library_Exception_If_Any, "__gnat_reraise_library_exception_if_any");
      begin
         Reraise_Library_Exception_If_Any;
      end;
   end finalize_library;

   procedure adafinal is
      procedure s_stalib_adafinal;
      pragma Import (C, s_stalib_adafinal, "system__standard_library__adafinal");

      procedure Runtime_Finalize;
      pragma Import (C, Runtime_Finalize, "__gnat_runtime_finalize");

   begin
      if not Is_Elaborated then
         return;
      end if;
      Is_Elaborated := False;
      Runtime_Finalize;
      s_stalib_adafinal;
   end adafinal;

   type No_Param_Proc is access procedure;

   procedure adainit is
      Main_Priority : Integer;
      pragma Import (C, Main_Priority, "__gl_main_priority");
      Time_Slice_Value : Integer;
      pragma Import (C, Time_Slice_Value, "__gl_time_slice_val");
      WC_Encoding : Character;
      pragma Import (C, WC_Encoding, "__gl_wc_encoding");
      Locking_Policy : Character;
      pragma Import (C, Locking_Policy, "__gl_locking_policy");
      Queuing_Policy : Character;
      pragma Import (C, Queuing_Policy, "__gl_queuing_policy");
      Task_Dispatching_Policy : Character;
      pragma Import (C, Task_Dispatching_Policy, "__gl_task_dispatching_policy");
      Priority_Specific_Dispatching : System.Address;
      pragma Import (C, Priority_Specific_Dispatching, "__gl_priority_specific_dispatching");
      Num_Specific_Dispatching : Integer;
      pragma Import (C, Num_Specific_Dispatching, "__gl_num_specific_dispatching");
      Main_CPU : Integer;
      pragma Import (C, Main_CPU, "__gl_main_cpu");
      Interrupt_States : System.Address;
      pragma Import (C, Interrupt_States, "__gl_interrupt_states");
      Num_Interrupt_States : Integer;
      pragma Import (C, Num_Interrupt_States, "__gl_num_interrupt_states");
      Unreserve_All_Interrupts : Integer;
      pragma Import (C, Unreserve_All_Interrupts, "__gl_unreserve_all_interrupts");
      Exception_Tracebacks : Integer;
      pragma Import (C, Exception_Tracebacks, "__gl_exception_tracebacks");
      Detect_Blocking : Integer;
      pragma Import (C, Detect_Blocking, "__gl_detect_blocking");
      Default_Stack_Size : Integer;
      pragma Import (C, Default_Stack_Size, "__gl_default_stack_size");
      Leap_Seconds_Support : Integer;
      pragma Import (C, Leap_Seconds_Support, "__gl_leap_seconds_support");

      procedure Runtime_Initialize (Install_Handler : Integer);
      pragma Import (C, Runtime_Initialize, "__gnat_runtime_initialize");

      Finalize_Library_Objects : No_Param_Proc;
      pragma Import (C, Finalize_Library_Objects, "__gnat_finalize_library_objects");
   begin
      if Is_Elaborated then
         return;
      end if;
      Is_Elaborated := True;
      Main_Priority := -1;
      Time_Slice_Value := -1;
      WC_Encoding := 'b';
      Locking_Policy := ' ';
      Queuing_Policy := ' ';
      Task_Dispatching_Policy := ' ';
      Priority_Specific_Dispatching :=
        Local_Priority_Specific_Dispatching'Address;
      Num_Specific_Dispatching := 0;
      Main_CPU := -1;
      Interrupt_States := Local_Interrupt_States'Address;
      Num_Interrupt_States := 0;
      Unreserve_All_Interrupts := 0;
      Exception_Tracebacks := 1;
      Detect_Blocking := 0;
      Default_Stack_Size := -1;
      Leap_Seconds_Support := 0;

      Runtime_Initialize (1);

      System.Scalar_Values.Initialize ('I', 'N');

      Finalize_Library_Objects := finalize_library'access;

      Gnat.Spelling_Checker'Elab_Body;
      E138 := E138 + 1;
      System.Soft_Links'Elab_Spec;
      System.Fat_Flt'Elab_Spec;
      E367 := E367 + 1;
      System.Fat_Llf'Elab_Spec;
      E119 := E119 + 1;
      System.Exception_Table'Elab_Body;
      E021 := E021 + 1;
      Ada.Containers'Elab_Spec;
      E533 := E533 + 1;
      Ada.Io_Exceptions'Elab_Spec;
      E059 := E059 + 1;
      Ada.Numerics'Elab_Spec;
      E363 := E363 + 1;
      Ada.Strings'Elab_Spec;
      E087 := E087 + 1;
      Ada.Strings.Maps'Elab_Spec;
      Ada.Strings.Maps.Constants'Elab_Spec;
      E092 := E092 + 1;
      Ada.Tags'Elab_Spec;
      Ada.Streams'Elab_Spec;
      E058 := E058 + 1;
      Interfaces.C'Elab_Spec;
      System.Exceptions'Elab_Spec;
      E023 := E023 + 1;
      System.File_Control_Block'Elab_Spec;
      E075 := E075 + 1;
      Ada.Streams.Stream_Io'Elab_Spec;
      E551 := E551 + 1;
      System.Finalization_Root'Elab_Spec;
      E068 := E068 + 1;
      Ada.Finalization'Elab_Spec;
      E066 := E066 + 1;
      System.Regpat'Elab_Spec;
      System.Storage_Pools'Elab_Spec;
      E203 := E203 + 1;
      System.Finalization_Masters'Elab_Spec;
      System.Storage_Pools.Subpools'Elab_Spec;
      System.Task_Info'Elab_Spec;
      E518 := E518 + 1;
      Ada.Calendar'Elab_Spec;
      Ada.Calendar'Elab_Body;
      E394 := E394 + 1;
      Ada.Calendar.Time_Zones'Elab_Spec;
      E400 := E400 + 1;
      Ada.Command_Line.Response_File'Elab_Spec;
      Gnat.Directory_Operations'Elab_Spec;
      System.Assertions'Elab_Spec;
      E150 := E150 + 1;
      System.Pool_Global'Elab_Spec;
      E211 := E211 + 1;
      E197 := E197 + 1;
      System.Finalization_Masters'Elab_Body;
      E199 := E199 + 1;
      E545 := E545 + 1;
      System.File_Io'Elab_Body;
      E064 := E064 + 1;
      E070 := E070 + 1;
      Ada.Tags'Elab_Body;
      E043 := E043 + 1;
      E089 := E089 + 1;
      System.Soft_Links'Elab_Body;
      E011 := E011 + 1;
      System.Os_Lib'Elab_Body;
      E072 := E072 + 1;
      System.Secondary_Stack'Elab_Body;
      E015 := E015 + 1;
      Gnat.Directory_Operations'Elab_Body;
      E082 := E082 + 1;
      E813 := E813 + 1;
      Ada.Strings.Unbounded'Elab_Spec;
      E191 := E191 + 1;
      Ada.Directories'Elab_Spec;
      Gnat.Expect'Elab_Spec;
      E540 := E540 + 1;
      System.Regexp'Elab_Spec;
      E218 := E218 + 1;
      Ada.Directories'Elab_Body;
      E392 := E392 + 1;
      E530 := E530 + 1;
      Gnat.Command_Line'Elab_Spec;
      System.Strings.Stream_Ops'Elab_Body;
      E549 := E549 + 1;
      Ada.Real_Time'Elab_Spec;
      Ada.Real_Time'Elab_Body;
      E499 := E499 + 1;
      Ada.Text_Io'Elab_Spec;
      Ada.Text_Io'Elab_Body;
      E056 := E056 + 1;
      Gnat.Command_Line'Elab_Body;
      E189 := E189 + 1;
      E469 := E469 + 1;
      Charset'Elab_Body;
      E132 := E132 + 1;
      Ocarina'Elab_Spec;
      E148 := E148 + 1;
      Errors'Elab_Spec;
      Ocarina.Analyzer.Aadl.Naming_Rules'Elab_Spec;
      Ocarina.Backends.Aadl_Xml'Elab_Spec;
      Ocarina.Backends.Ada_Tree.Nodes'Elab_Spec;
      Ocarina.Backends.Ada_Tree.Nutils'Elab_Spec;
      Ocarina.Backends.Ada_Values'Elab_Spec;
      Ocarina.Backends.Arinc653_Conf'Elab_Spec;
      Ocarina.Backends.Asn1'Elab_Spec;
      Ocarina.Backends.Asn1_Tree.Nodes'Elab_Spec;
      Ocarina.Backends.Asn1_Values'Elab_Spec;
      Ocarina.Backends.Asn1_Tree.Nutils'Elab_Spec;
      Ocarina.Backends.C_Tree.Nodes'Elab_Spec;
      Ocarina.Backends.C_Tree.Nutils'Elab_Spec;
      Ocarina.Backends.C_Values'Elab_Spec;
      Ocarina.Backends.Cheddar'Elab_Spec;
      Ocarina.Backends.Connection_Matrix'Elab_Spec;
      Ocarina.Backends.Connection_Matrix.Main'Elab_Spec;
      Ocarina.Backends.Deos_Conf'Elab_Spec;
      Ocarina.Backends.Functions_Matrix'Elab_Spec;
      Ocarina.Backends.Functions_Matrix.Main'Elab_Spec;
      Ocarina.Backends.Lnt'Elab_Spec;
      Ocarina.Backends.Lnt.Nodes'Elab_Spec;
      Ocarina.Backends.Lnt.Nutils'Elab_Spec;
      Ocarina.Backends.Mast'Elab_Spec;
      Ocarina.Backends.Mast_Tree.Nodes'Elab_Spec;
      Ocarina.Backends.Mast_Tree.Nutils'Elab_Spec;
      Ocarina.Backends.Mast_Values'Elab_Spec;
      Ocarina.Backends.Pn'Elab_Spec;
      Ocarina.Backends.Pn.Nodes'Elab_Spec;
      E674 := E674 + 1;
      E683 := E683 + 1;
      E676 := E676 + 1;
      Ocarina.Backends.Po_Hi_Ada'Elab_Spec;
      Ocarina.Backends.Pok_C'Elab_Spec;
      Ocarina.Backends.Pok_Cheddar'Elab_Spec;
      Ocarina.Backends.Build_Utils'Elab_Spec;
      Ocarina.Backends.Execution_Tests'Elab_Spec;
      Ocarina.Backends.Execution_Utils'Elab_Spec;
      Ocarina.Backends.Stats'Elab_Spec;
      Ocarina.Backends.Stats.Main'Elab_Spec;
      Ocarina.Backends.Subprograms'Elab_Spec;
      Ocarina.Backends.Vxworks653_Conf'Elab_Spec;
      Ocarina.Backends.Xml_Tree.Nodes'Elab_Spec;
      Ocarina.Backends.Xml_Tree.Nutils'Elab_Spec;
      Ocarina.Backends.Xml_Values'Elab_Spec;
      Ocarina.Backends.Xtratum_Conf'Elab_Spec;
      Ocarina.Fe_Real.Parser'Elab_Spec;
      Ocarina.Files'Elab_Spec;
      E771 := E771 + 1;
      E619 := E619 + 1;
      E587 := E587 + 1;
      E581 := E581 + 1;
      E452 := E452 + 1;
      E375 := E375 + 1;
      Ocarina.Instances.Real_Checker.Queries'Elab_Spec;
      Ocarina.Me_Aadl.Aadl_Instances.Nodes'Elab_Spec;
      E438 := E438 + 1;
      E805 := E805 + 1;
      E789 := E789 + 1;
      E565 := E565 + 1;
      Ocarina.Backends.Po_Hi_C.Request'Elab_Body;
      E579 := E579 + 1;
      E703 := E703 + 1;
      E599 := E599 + 1;
      E595 := E595 + 1;
      E593 := E593 + 1;
      E583 := E583 + 1;
      Ocarina.Backends.C_Common.Subprograms'Elab_Body;
      E487 := E487 + 1;
      E450 := E450 + 1;
      Ocarina.Backends.Arinc653_Conf.Partitions'Elab_Body;
      E446 := E446 + 1;
      E444 := E444 + 1;
      E442 := E442 + 1;
      E440 := E440 + 1;
      E433 := E433 + 1;
      Ocarina.Me_Aadl.Aadl_Tree.Nodes'Elab_Spec;
      E713 := E713 + 1;
      E253 := E253 + 1;
      E251 := E251 + 1;
      E259 := E259 + 1;
      E243 := E243 + 1;
      Ocarina.Aadl_Values'Elab_Spec;
      E273 := E273 + 1;
      E255 := E255 + 1;
      E245 := E245 + 1;
      E262 := E262 + 1;
      E249 := E249 + 1;
      E247 := E247 + 1;
      E257 := E257 + 1;
      E239 := E239 + 1;
      E241 := E241 + 1;
      E277 := E277 + 1;
      E293 := E293 + 1;
      E291 := E291 + 1;
      E849 := E849 + 1;
      E289 := E289 + 1;
      E287 := E287 + 1;
      E285 := E285 + 1;
      E283 := E283 + 1;
      E841 := E841 + 1;
      E279 := E279 + 1;
      E825 := E825 + 1;
      E312 := E312 + 1;
      E306 := E306 + 1;
      Ocarina.Me_Aadl_Ba.Ba_Tree.Nodes'Elab_Spec;
      E908 := E908 + 1;
      E894 := E894 + 1;
      E902 := E902 + 1;
      E898 := E898 + 1;
      Ocarina.Me_Aadl_Ema.Ema_Tokens'Elab_Spec;
      E912 := E912 + 1;
      Ocarina.Me_Aadl_Ema.Ema_Tree.Nodes'Elab_Spec;
      E331 := E331 + 1;
      Ocarina.Ema_Values'Elab_Spec;
      Ocarina.Me_Aadl_Ema.Ema_Tree.Nutils'Elab_Spec;
      E325 := E325 + 1;
      Ocarina.Me_Ao4aadl.Ao4aadl_Tree.Nodes'Elab_Spec;
      Ocarina.Ao4aadl_Values'Elab_Spec;
      Ocarina.Me_Ao4aadl.Ao4aadl_Tree.Nutils'Elab_Spec;
      E930 := E930 + 1;
      Ocarina.Me_Ao4aadl.Tokens'Elab_Spec;
      Ocarina.Me_Real.Real_Tree.Nodes'Elab_Spec;
      Ocarina.Me_Real.Real_Tree.Nutils'Elab_Spec;
      Ocarina.Analyzer.Real.Finder'Elab_Spec;
      Ocarina.Me_Real.Tokens'Elab_Spec;
      E859 := E859 + 1;
      Ocarina.Namet'Elab_Spec;
      E938 := E938 + 1;
      Ocarina.Ao4aadl_Values'Elab_Body;
      E926 := E926 + 1;
      E338 := E338 + 1;
      Ocarina.Ema_Values'Elab_Body;
      E916 := E916 + 1;
      E299 := E299 + 1;
      E321 := E321 + 1;
      Ocarina.Aadl_Values'Elab_Body;
      E110 := E110 + 1;
      E358 := E358 + 1;
      E281 := E281 + 1;
      E809 := E809 + 1;
      E803 := E803 + 1;
      E807 := E807 + 1;
      E795 := E795 + 1;
      Ocarina.Backends.Xml_Values'Elab_Body;
      E386 := E386 + 1;
      E793 := E793 + 1;
      E791 := E791 + 1;
      E787 := E787 + 1;
      E783 := E783 + 1;
      E785 := E785 + 1;
      E781 := E781 + 1;
      E779 := E779 + 1;
      Ocarina.Backends.Utils'Elab_Body;
      E390 := E390 + 1;
      Ocarina.Backends.Subprograms'Elab_Body;
      E777 := E777 + 1;
      E775 := E775 + 1;
      Ocarina.Backends.Stats.Main'Elab_Body;
      E773 := E773 + 1;
      Ocarina.Backends.Properties.Arinc653'Elab_Body;
      E617 := E617 + 1;
      E532 := E532 + 1;
      E435 := E435 + 1;
      Ocarina.Backends.Pok_Cheddar'Elab_Body;
      E567 := E567 + 1;
      Ocarina.Backends.Pok_C.Main'Elab_Body;
      E561 := E561 + 1;
      E555 := E555 + 1;
      Ocarina.Backends.Po_Hi_C.Marshallers'Elab_Body;
      E575 := E575 + 1;
      Ocarina.Backends.Po_Hi_C.Main'Elab_Body;
      E573 := E573 + 1;
      Ocarina.Backends.Po_Hi_C.Activity'Elab_Body;
      E569 := E569 + 1;
      E707 := E707 + 1;
      E705 := E705 + 1;
      Ocarina.Backends.Po_Hi_Ada.Runtime'Elab_Body;
      E693 := E693 + 1;
      E701 := E701 + 1;
      E699 := E699 + 1;
      E697 := E697 + 1;
      Ocarina.Backends.Po_Hi_Ada.Deployment'Elab_Body;
      E695 := E695 + 1;
      Ocarina.Backends.Po_Hi_Ada.Activity'Elab_Body;
      E689 := E689 + 1;
      Ocarina.Backends.Mast_Values'Elab_Body;
      E658 := E658 + 1;
      Ocarina.Backends.Mast_Tree.Nutils'Elab_Body;
      E660 := E660 + 1;
      E651 := E651 + 1;
      E649 := E649 + 1;
      E647 := E647 + 1;
      E641 := E641 + 1;
      Ocarina.Backends.Functions_Matrix.Main'Elab_Body;
      E621 := E621 + 1;
      E615 := E615 + 1;
      E591 := E591 + 1;
      Ocarina.Backends.Connection_Matrix.Main'Elab_Body;
      E589 := E589 + 1;
      Ocarina.Backends.C_Values'Elab_Body;
      E483 := E483 + 1;
      Ocarina.Backends.C_Common.Types'Elab_Body;
      E491 := E491 + 1;
      Ocarina.Backends.Asn1_Tree.Nutils'Elab_Body;
      E461 := E461 + 1;
      Ocarina.Backends.Asn1_Values'Elab_Body;
      E463 := E463 + 1;
      Ocarina.Backends.Arinc653_Conf.Scheduling'Elab_Body;
      E448 := E448 + 1;
      E431 := E431 + 1;
      Ocarina.Backends.Alloy'Elab_Body;
      E429 := E429 + 1;
      Ocarina.Backends.Ada_Values'Elab_Body;
      E415 := E415 + 1;
      E379 := E379 + 1;
      E377 := E377 + 1;
      Ocarina.Annotations'Elab_Body;
      E170 := E170 + 1;
      E329 := E329 + 1;
      E229 := E229 + 1;
      Ocarina.Analyzer'Elab_Body;
      E221 := E221 + 1;
      E168 := E168 + 1;
      E108 := E108 + 1;
      Ocarina.Fe_Aadl_Ema.Lexer'Elab_Body;
      E918 := E918 + 1;
      Ocarina.Fe_Ao4aadl.Lexer'Elab_Body;
      E936 := E936 + 1;
      Ocarina.Fe_Real.Lexer'Elab_Spec;
      E863 := E863 + 1;
      Ocarina.Me_Aadl.Tokens'Elab_Spec;
      E767 := E767 + 1;
      E745 := E745 + 1;
      Ocarina.Fe_Aadl.Lexer'Elab_Spec;
      E815 := E815 + 1;
      E833 := E833 + 1;
      E847 := E847 + 1;
      E853 := E853 + 1;
      E851 := E851 + 1;
      E831 := E831 + 1;
      E845 := E845 + 1;
      E843 := E843 + 1;
      E829 := E829 + 1;
      E827 := E827 + 1;
      E837 := E837 + 1;
      E839 := E839 + 1;
      Ocarina.Me_Aadl_Ba.Tokens'Elab_Spec;
      E296 := E296 + 1;
      Ocarina.Fe_Aadl_Ba.Lexer'Elab_Spec;
      Ocarina.Fe_Aadl_Ba.Lexer'Elab_Body;
      E889 := E889 + 1;
      E904 := E904 + 1;
      E900 := E900 + 1;
      E896 := E896 + 1;
      E906 := E906 + 1;
      E891 := E891 + 1;
      Ocarina.Options'Elab_Spec;
      E266 := E266 + 1;
      E821 := E821 + 1;
      E301 := E301 + 1;
      Ocarina.Output'Elab_Body;
      E142 := E142 + 1;
      E910 := E910 + 1;
      E881 := E881 + 1;
      E873 := E873 + 1;
      E879 := E879 + 1;
      E877 := E877 + 1;
      E875 := E875 + 1;
      E857 := E857 + 1;
      Ocarina.Fe_Aadl.Lexer'Elab_Body;
      E819 := E819 + 1;
      E749 := E749 + 1;
      E747 := E747 + 1;
      E763 := E763 + 1;
      E761 := E761 + 1;
      E759 := E759 + 1;
      E743 := E743 + 1;
      E757 := E757 + 1;
      E755 := E755 + 1;
      E753 := E753 + 1;
      E751 := E751 + 1;
      E739 := E739 + 1;
      E741 := E741 + 1;
      Ocarina.Namet'Elab_Body;
      E136 := E136 + 1;
      E865 := E865 + 1;
      E940 := E940 + 1;
      E920 := E920 + 1;
      Ocarina.Backends.Execution_Tests'Elab_Body;
      E497 := E497 + 1;
      Ocarina.Backends.Pok_C.Makefile'Elab_Body;
      E563 := E563 + 1;
      E493 := E493 + 1;
      E485 := E485 + 1;
      E681 := E681 + 1;
      E664 := E664 + 1;
      E417 := E417 + 1;
      E662 := E662 + 1;
      Ocarina.Backends'Elab_Body;
      E373 := E373 + 1;
      E077 := E077 + 1;
      E922 := E922 + 1;
      E885 := E885 + 1;
      E407 := E407 + 1;
      E457 := E457 + 1;
      E474 := E474 + 1;
      E625 := E625 + 1;
      E654 := E654 + 1;
      E670 := E670 + 1;
      E672 := E672 + 1;
      E679 := E679 + 1;
      E666 := E666 + 1;
      E382 := E382 + 1;
      E183 := E183 + 1;
      E179 := E179 + 1;
      E635 := E635 + 1;
      E231 := E231 + 1;
      E164 := E164 + 1;
      E185 := E185 + 1;
      E356 := E356 + 1;
      E223 := E223 + 1;
      E871 := E871 + 1;
      E317 := E317 + 1;
      E334 := E334 + 1;
      E932 := E932 + 1;
      E347 := E347 + 1;
      E351 := E351 + 1;
      E349 := E349 + 1;
      E887 := E887 + 1;
      E823 := E823 + 1;
      Ocarina.Fe_Ao4aadl.Parser'Elab_Body;
      E924 := E924 + 1;
      Ocarina.Fe_Aadl_Ema.Parser'Elab_Body;
      E914 := E914 + 1;
      E310 := E310 + 1;
      E235 := E235 + 1;
      Ocarina.Parser'Elab_Body;
      E855 := E855 + 1;
      E835 := E835 + 1;
      E817 := E817 + 1;
      E765 := E765 + 1;
      E227 := E227 + 1;
      Ocarina.Real_Expander.Flow_Analysis'Elab_Body;
      E371 := E371 + 1;
      Ocarina.Real_Values'Elab_Spec;
      Ocarina.Real_Values'Elab_Body;
      E362 := E362 + 1;
      E369 := E369 + 1;
      E729 := E729 + 1;
      Ocarina.Fe_Real.Parser'Elab_Body;
      E861 := E861 + 1;
      E344 := E344 + 1;
      Ocarina.Analyzer.Real'Elab_Body;
      E340 := E340 + 1;
      E883 := E883 + 1;
      Ocarina.Transfo'Elab_Spec;
      Ocarina.Transfo.Fusions'Elab_Spec;
      E869 := E869 + 1;
      Ocarina.Transfo.Fusions.Scheduler'Elab_Spec;
      Ocarina.Transfo.Fusions.Scheduler'Elab_Body;
      E946 := E946 + 1;
      Ocarina.Transfo.Move'Elab_Body;
      E948 := E948 + 1;
      Ocarina.Transfo.Optim.Eval'Elab_Spec;
      Ocarina.Transfo.Optim.Eval'Elab_Body;
      E952 := E952 + 1;
      Ocarina.Transfo.Optim'Elab_Body;
      E950 := E950 + 1;
      E867 := E867 + 1;
      E268 := E268 + 1;
      E264 := E264 + 1;
      E633 := E633 + 1;
      E631 := E631 + 1;
      E465 := E465 + 1;
      E174 := E174 + 1;
      Ocarina.Utils'Elab_Body;
      E954 := E954 + 1;
      Ocarina.Transfo.Fusions'Elab_Body;
      E944 := E944 + 1;
      E942 := E942 + 1;
      E271 := E271 + 1;
      E934 := E934 + 1;
      E336 := E336 + 1;
      E319 := E319 + 1;
      E166 := E166 + 1;
      E181 := E181 + 1;
      E384 := E384 + 1;
      E668 := E668 + 1;
      E656 := E656 + 1;
      E627 := E627 + 1;
      E476 := E476 + 1;
      E459 := E459 + 1;
      E409 := E409 + 1;
      E737 := E737 + 1;
      E304 := E304 + 1;
      E342 := E342 + 1;
      Ocarina.Me_Real.Real_Tree.Nutils'Elab_Body;
      E353 := E353 + 1;
      E327 := E327 + 1;
      E187 := E187 + 1;
      E233 := E233 + 1;
      E360 := E360 + 1;
      Ocarina.Backends.Properties.Utils'Elab_Body;
      E423 := E423 + 1;
      E177 := E177 + 1;
      E237 := E237 + 1;
      E801 := E801 + 1;
      E799 := E799 + 1;
      E797 := E797 + 1;
      Ocarina.Backends.Xml_Tree.Nutils'Elab_Body;
      E388 := E388 + 1;
      E427 := E427 + 1;
      E735 := E735 + 1;
      Ocarina.Backends.Replication_Properties'Elab_Body;
      E769 := E769 + 1;
      E691 := E691 + 1;
      E597 := E597 + 1;
      E481 := E481 + 1;
      Ocarina.Backends.Build_Utils'Elab_Body;
      E471 := E471 + 1;
      Ocarina.Backends.Properties'Elab_Body;
      E421 := E421 + 1;
      Ocarina.Backends.Pok_C.Runtime'Elab_Body;
      E557 := E557 + 1;
      Ocarina.Backends.Pok_C.Deployment'Elab_Body;
      E559 := E559 + 1;
      Ocarina.Backends.Po_Hi_C.Runtime'Elab_Body;
      E489 := E489 + 1;
      Ocarina.Backends.Po_Hi_C.Naming'Elab_Body;
      E577 := E577 + 1;
      Ocarina.Backends.Po_Hi_C.Deployment'Elab_Body;
      E571 := E571 + 1;
      E685 := E685 + 1;
      E645 := E645 + 1;
      E643 := E643 + 1;
      E637 := E637 + 1;
      Ocarina.Backends.Lnt.Nutils'Elab_Body;
      E629 := E629 + 1;
      E639 := E639 + 1;
      E623 := E623 + 1;
      E425 := E425 + 1;
      E585 := E585 + 1;
      Ocarina.Backends.C_Tree.Nutils'Elab_Body;
      E478 := E478 + 1;
      E495 := E495 + 1;
      E467 := E467 + 1;
      Ocarina.Backends.Asn1.Deployment'Elab_Body;
      E454 := E454 + 1;
      Ocarina.Backends.Ada_Tree.Nutils'Elab_Body;
      E411 := E411 + 1;
      E687 := E687 + 1;
      E314 := E314 + 1;
      E308 := E308 + 1;
      E225 := E225 + 1;
      E811 := E811 + 1;
      Ocarina.Instances.Real_Checker.Queries.Access_Predicates'Elab_Spec;
      E711 := E711 + 1;
      Ocarina.Instances.Real_Checker.Queries.Bound_Predicates'Elab_Spec;
      E715 := E715 + 1;
      Ocarina.Instances.Real_Checker.Queries.Call_Predicates'Elab_Spec;
      E717 := E717 + 1;
      Ocarina.Instances.Real_Checker.Queries.Connected_Predicates'Elab_Spec;
      E719 := E719 + 1;
      Ocarina.Instances.Real_Checker.Queries.Passing_Predicates'Elab_Spec;
      E721 := E721 + 1;
      Ocarina.Instances.Real_Checker.Queries.Predecessor_Predicates'Elab_Spec;
      E723 := E723 + 1;
      Ocarina.Instances.Real_Checker.Queries.Provided_Class_Predicates'Elab_Spec;
      E725 := E725 + 1;
      Ocarina.Instances.Real_Checker.Queries.Subcomponent_Predicates'Elab_Spec;
      E727 := E727 + 1;
      Ocarina.Backends.Real'Elab_Body;
      E709 := E709 + 1;
   end adainit;

   procedure Ada_Main_Program;
   pragma Import (Ada, Ada_Main_Program, "_ada_ocarina_cmd");

   function main
     (argc : Integer;
      argv : System.Address;
      envp : System.Address)
      return Integer
   is
      procedure Initialize (Addr : System.Address);
      pragma Import (C, Initialize, "__gnat_initialize");

      procedure Finalize;
      pragma Import (C, Finalize, "__gnat_finalize");
      SEH : aliased array (1 .. 2) of Integer;

      Ensure_Reference : aliased System.Address := Ada_Main_Program_Name'Address;
      pragma Volatile (Ensure_Reference);

   begin
      gnat_argc := argc;
      gnat_argv := argv;
      gnat_envp := envp;

      Initialize (SEH'Address);
      adainit;
      Ada_Main_Program;
      adafinal;
      Finalize;
      return (gnat_exit_status);
   end;

--  BEGIN Object file/option list
   --   /home/hugues/Dev/ocarina/src/main/objects/ocarina_cmd.o
   --   /home/hugues/Dev/ocarina/src/main/objects/ocarina-scripts.o
   --   /home/hugues/Dev/ocarina/src/main/objects/ocarina-utils.o
   --   /home/hugues/Dev/ocarina/src/main/objects/ocarina-cmd_line.o
   --   -L/home/hugues/Dev/ocarina/src/main/objects/
   --   -L/home/hugues/Dev/ocarina/src/main/objects/
   --   -L/home/hugues/Dev/ocarina/src/core/libs/
   --   -L/home/hugues/Dev/ocarina/src/config/libs/
   --   -L/home/hugues/Dev/ocarina/src/frontends/libs/
   --   -L/home/hugues/Dev/ocarina/src/backends/libs/
   --   -L/home/hugues/Dev/ocarina/src/transfo/libs/
   --   -L/home/prise/opt/x86_64/gcc-5.2/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/adalib/
   --   -static
   --   -lgnarl
   --   -lgnat
   --   -lpthread
   --   -lrt
--  END Object file/option list   

end ada_main;
