<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>AADL support -- by Julien Delange &lt;delange@enst.fr&gt; -- feel free to use and modify</string>
	<key>fileTypes</key>
	<array>
		<string>aadl</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\b(?i:(package|system|process|data|device|thread|thread group|subprogram))\b</string>
	<key>foldingStopMarker</key>
	<string>\b(?i:(end .*))\b</string>
	<key>name</key>
	<string>AADL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.aadl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.aadl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i:(virtual bus|virtual processor|bus|process|thread|thread group|data|system|subprogram|processor|))\b\s+(\w+(\.\w+)?|"(?:\+|-|=|\*|/)")</string>
			<key>name</key>
			<string>meta.componenttype.aadl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.package.ada</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.body.ada</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.package.ada</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i:(package|properties)(?:\b\s+(body))?)\b\s+(\w+(\.\w+)?|"(?:\+|-|=|\*|/)")</string>
			<key>name</key>
			<string>meta.function.aadl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.ada</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ada</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i:(end))\b\s+(\w+(\.\w+)?|"(\+|-|=|\*|/)")\s?;</string>
			<key>name</key>
			<string>meta.function.aadl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(\=&gt;|public|private))\b</string>
			<key>name</key>
			<string>keyword.others.aadl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(\=&gt;|features|properties|connections|subcomponents|port|event|data|))\b</string>
			<key>name</key>
			<string>keyword.componentspecs.aadl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.aadl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(--)(.*)$\n?</string>
			<key>name</key>
			<string>comment.double-dash.aadl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.aadl</string>
	<key>uuid</key>
	<string>F0670B68-8465-49C6-AD47-96A099F46414</string>
</dict>
</plist>
