name: Ocarina + Python / Ubuntu (default GNAT)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Set up GNAT toolchain (Ubuntu default distribution)
      run: >
        sudo apt-get update &&
        sudo apt-get install gnat gprbuild libgnatcoll-python16.1.0-dev

    - name: Set up ocarina-builder
      run: >
       git clone https://github.com/OpenAADL/ocarina-build.git

    - name: Build
      run: ( cd ocarina-build ; ./build_ocarina.sh --scenario=github --remote=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY )
